- docs/topics/security.md
> Application Security

- docs/topics/developer-workflow.md
> Developer Workflow

- docs/topics/code-quality.md
> Code Quality

- docs/topics/data-persistence.md
> Data Persistence

- docs/topics/git.md
- docs/topics/github.md
> Fixed formatting issues

- docs/topics/code-quality.md
Commented out code should never be committed nor accepted in a PR
> Add committed commented code quality section

- .github/workflows/main.yml
- .github/workflows/markdown-linting.yml
- .markdownlint.json
- README.md
- docs/index.md
- docs/topics/code-quality.md
- docs/topics/data-persistence.md
- docs/topics/developer-workflow.md
- docs/topics/git.md
- docs/topics/github.md
- docs/topics/node-js.md
- docs/topics/programming-languages.md
- docs/topics/security.md
- docs/topics/third-party-services.md
- docs/topics/writing-standards.md
Added a linting check for the Markdown which runs during pull requests and merges to master.
Fixed all the linting issues as well, I think.
> Node js formatting

- mkdocs.yml
> Added Web API Frameworks

- docs/index.md
- docs/topics/writing-standards.md
- mkdocs.yml
- requirements.txt
I couldn't resist. I think this theme is much nicer and has a bunch of nice plugins to create richer content.
> Changed the theme and tweaked some plugins

- docs/topics/github.md
- more specific about main branch
> Update protected branches setup

- docs/topics/data-persistence.md
Discussed and ratified February 13th, 2020
> Prohibit MongoDB

- docs/topics/programming-languages.md
- Cleaned up the documentation to make it more clear as to what is allowed
- Added Flask and Express as allowed frameworks
> Add Flask and Express as permitted frameworks

- docs/topics/node-js.md
> Added NJ-110

- Pipfile
- Pipfile.lock
- docs/index.md
- Add local env setup instructions
- add Pipfile
> add setup section

- docs/topics/third-party-services.md
Added a new item to list approved 3rd party DNS providers.
Closes #73
> Added 3rd party DNS providers item

- docs/topics/code-quality.md
Reinforcing the importance of never hardcoding anything resembling data.
> Added item forbidding hardcoding of data

- docs/topics/react.md
Apollo client has built-in state management. This is nice when using the Apollo Client for GraphQL APIs as you can do local state management with the same library.
> Added Apollo client state management

- docs/topics/git.md
Branch naming standard; closes #49
> Branch naming standard item

- docs/topics/developer-workflow.md
Adding a git workflow video to the developer workflow page
> add git workflow video

- docs/topics/node-js.md
> (NJ-300) Always Commit Lock Files

- .markdownlint.json
- .markdownlint.yml
- docs/topics/code-quality.md
Added some additional exceptions:
- Method lines 25 -> 50
- Disable similar code check
- Allow filtering of generated code
> Code climate filters

- docs/topics/react.md
Added Cypress as an officially permitted testing framework
> Added Cypress
